resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: carvedrock-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - Serilog__MinimumLevel__Default=Information
    - Serilog__MinimumLevel__Override__Microsoft=Warning
    - Serilog__MinimumLevel__Override__Microsoft.Hosting=Information
    - Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore.Database.Command=Information
    - Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore.Query=Information
    - Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore.Update=Information
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=carvedrock-api
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: carvedrock-api-secrets
  envs:
  - .carvedrock-api.secrets
