# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      ## optional - use aspirate to publish based on app host
      ## repository names come from prefix below and service name string in app host
      - name: Install Aspirate
        run: dotnet tool install -g aspirate --prerelease

      - name: Aspirate Build (build and push images)
        run: |
          aspirate build -m ./manifest.json \
          --non-interactive \
          --disable-secrets \
          --container-repostiory-prefix=dahlsailrunner \
          --container-image-tag=${{ github.run_number }} \
          --container-registry=docker.io
        working-directory: ./aspire/CarvedRock-Aspire.AppHost
        env:
          SDK_CONTAINER_REGISTRY_UNAME: dahlsailrunner
          SDK_CONTAINER_REGISTRY_PWORD: ${{ secrets.DOCKER_PASSWORD }}

      # optional -- manually publish with dotnet publish.
      # repeat for all three images
      - name: .NET Publish API container
        if: ${{ false }}
        run: |
          dotnet publish /t:PublishContainer \
          --os linux \
          --arch x64 \
          -p ContainerRegistry=docker.io \
          -p ContainerRepository=dahlsailrunner/carvedrock-api \
          -p ContainerImageTag=${{ github.run_number }}
        working-directory: ./aspire/CarvedRock.Api
        env:
          SDK_CONTAINER_REGISTRY_UNAME: dahlsailrunner
          SDK_CONTAINER_REGISTRY_PWORD: ${{ secrets.DOCKER_PASSWORD }}
